# Generated by Django 4.1.2 on 2022-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='приватный'),
        ),
    ]
