# Generated by Django 4.1.2 on 2022-12-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
