# Generated by Django 4.1.2 on 2022-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='ссылка на картинку'),
        ),
    ]
