# Generated by Django 4.1.2 on 2022-12-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.URLField(max_length=500, null=True, verbose_name='ссылка на картинку'),
        ),
    ]
