# Generated by Django 4.1.2 on 2022-12-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name=''),
        ),
    ]
