# Generated by Django 4.1.2 on 2022-11-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_chat_users_remove_message_recieved_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='received_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='role',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
