# Generated by Django 4.1.2 on 2022-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка на голосовое сообщение'),
        ),
    ]
