# Generated by Django 4.1.2 on 2022-12-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='текст'),
        ),
    ]
