# Generated by Django 4.1.2 on 2022-11-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_chat_options_alter_chatmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chats.chat', verbose_name='чат'),
        ),
    ]
