# Generated by Django 4.1.2 on 2022-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_chatmember_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='приватный'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.URLField(max_length=500, null=True, verbose_name='ссылка на картинку'),
        ),
    ]
