# Generated by Django 4.1.2 on 2022-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLastMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Число новых пользователей зай последний месяц')),
            ],
        ),
    ]
