# Generated by Django 4.1.2 on 2022-12-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userslastmonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersLastMonth',
        ),
    ]
